[package]
name = "omen-fan"
version = "0.7.0"
edition = "2024"

[dependencies]
nix = { version = "0.29", features = ["user"] }
serde = "1.0.219"
toml = "0.8.20"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"

[features]
default = ["default_ec"]
acpi_ec = []
default_ec = []