[package]
name = "omen-fan"
version = "0.7.0"
edition = "2024"

[dependencies]
nix = { version = "0.29", features = ["user"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"

