name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: omen-fan

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release --features "acpi_ec,default_mode"
    - name: List files
      run: ls -ail target/release/
    - run: mkdir -p /omen-fan/artifact
    - run: cp target/release/omen-fan /omen-fan/artifact/
    - name: Upload build
      uses: actions/upload-artifact@v4.6.2
      with:
        name: omen-fan
        path: /omen-fan/artifact/
